import path from "node:path";
import { selectNextSlice } from "./select";
import type { EmberState } from "./types";

export function renderMemory(state: EmberState): string {
  const lines: string[] = [];

  lines.push("# Ember");
  lines.push("");
  lines.push(
    "Generated by Ember. This file is the current project memory, not a historical log."
  );
  lines.push("");

  addSection(lines, "Project Reality", renderProjectReality(state));
  addSection(lines, "Validated Paths", renderValidatedPaths(state));
  addSection(lines, "Open PRDs", renderOpenPrds(state));
  addSection(lines, "Open Slices", renderOpenSlices(state));
  addSection(lines, "Recent Learnings", renderLearnings(state.learnings));
  addSection(lines, "Next Slice", renderNextSlice(state));

  return lines.join("\n");
}

export async function writeMemory(
  projectRoot: string,
  state: EmberState
): Promise<void> {
  const content = renderMemory(state);
  await Bun.write(path.join(projectRoot, "EMBER.md"), content);
}

// --- Section renderers ---

function renderProjectReality(state: EmberState): string[] {
  const bullets: string[] = [];
  for (const prd of Object.values(state.prds)) {
    if (prd.status === "archived") continue;
    const criteria = Object.values(prd.criteria);
    const doneCount = criteria.filter((criterion) => criterion.status === "done").length;
    const label = getPrdStatusLabel(prd.status, doneCount, criteria.length);
    bullets.push(`- **${prd.title}** (${prd.id}): ${label}`);
  }
  return bullets.length > 0 ? bullets : ["- No PRDs loaded"];
}

function getPrdStatusLabel(
  status: string,
  doneCount: number,
  totalCount: number
): string {
  if (status === "completed") return "complete";
  if (doneCount > 0) return `${doneCount}/${totalCount} criteria done`;
  return "not started";
}

function renderValidatedPaths(state: EmberState): string[] {
  const tracers = Object.values(state.slices).filter(
    (slice) => slice.kind === "tracer" && slice.status === "done"
  );
  if (tracers.length === 0) return ["- None yet"];
  return tracers.map((tracer) => `- ${tracer.title} (${tracer.id})`);
}

function renderOpenPrds(state: EmberState): string[] {
  const open = Object.values(state.prds).filter(
    (prd) => prd.status !== "completed" && prd.status !== "archived"
  );
  if (open.length === 0) return ["- All PRDs complete"];
  return open.map((prd) => {
    const remaining = Object.values(prd.criteria).filter(
      (criterion) => criterion.status === "pending"
    ).length;
    return `- ${prd.title} (${prd.id}): ${remaining} criteria remaining`;
  });
}

function renderOpenSlices(state: EmberState): string[] {
  const open = Object.values(state.slices).filter(
    (slice) => slice.status === "pending" || slice.status === "running"
  );
  if (open.length === 0) return ["- No open slices"];
  return open.map(
    (slice) => `- [${slice.kind}] ${slice.title} (${slice.id}) — ${slice.status}`
  );
}

function renderLearnings(recentLearnings: string[]): string[] {
  // Show only last 10 to keep EMBER.md concise
  const learnings = recentLearnings.slice(-10);
  if (learnings.length === 0) return ["- No learnings recorded yet"];
  return learnings.map((learning) => `- ${learning}`);
}

function renderNextSlice(state: EmberState): string[] {
  const next = selectNextSlice(state);
  if (!next) return ["- No actionable slices"];
  return [`- **${next.title}** (${next.id}) [${next.kind}] for PRD ${next.prdId}`];
}

// --- Helpers ---

function addSection(lines: string[], heading: string, content: string[]): void {
  lines.push(`## ${heading}`);
  lines.push("");
  lines.push(...content);
  lines.push("");
}
